#*****************CURR_FILE_DIR*****************
# Get directory of current script file, follow symlink if needed.
CURR_FILE="${(%):-%N}"
if [ -L ${CURR_FILE} ]; then
	CURR_FILE=`readlink ${CURR_FILE}`
fi
CURR_FILE_DIR="$(cd "$(dirname "${CURR_FILE}" )" && pwd )"
#*****************CURR_FILE_DIR*****************

source ${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile

unset CURR_FILE_DIR
