#*****************CURR_FILE_DIR*****************
# Get directory of current script file, follow symlink if needed.
CURR_FILE="${(%):-%N}"
if [ -L ${CURR_FILE} ]; then
	CURR_FILE=`readlink ${CURR_FILE}`
fi
CURR_FILE_DIR="$(cd "$(dirname "${CURR_FILE}" )" && pwd )"
#*****************CURR_FILE_DIR*****************

source ${CURR_FILE_DIR}/shellrc.zsh
source ${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc

unset CURR_FILE_DIR

if [ -e ~/.zshrc.local ]; then
	source ~/.zshrc.local
fi
