#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

CLIENT_IP=`echo $SSH_CLIENT | awk '{ print $1}'`

if [ $# -eq 2 ]; then
    CLIENT_TARGET_PATH=$2
elif [ $# -eq 1 ]; then
    CLIENT_TARGET_PATH=${SYNC_TO_CLIENT_TARGET_PATH}
else
    echo "Illegal number of arguments!"
    exit 1
fi

SOURCE_PATH=`readlink -f $1`

rsync -Prz $SOURCE_PATH ${USER}@${CLIENT_IP}:${CLIENT_TARGET_PATH}
